services:
  website:
    image: nginx:alpine
    container_name: jonzor-website
    restart: unless-stopped
    ports:
      - '8081:80' # Kept so you can still view it locally/via Tailscale
    volumes:
      - ./website-files:/usr/share/nginx/html
      - /mnt/moln/nextcloud/nextcloud_data/data/jonzor/files/Laptop_pictures/Website_Icons/Portfolio_Jonzor:/usr/share/nginx/html/assets/icons:ro

  files:
    image: httpd:alpine
    container_name: jonzor-files
    restart: unless-stopped
    ports:
      - '8082:80' # Kept so you can still view it locally/via Tailscale
    volumes:
      - ./file-data:/usr/local/apache2/htdocs/
      - ./my-httpd.conf:/usr/local/apache2/conf/httpd.conf
      - /mnt/moln/nextcloud/nextcloud_data/data/jonzor/files/Laptop_pictures/Website_Icons/Files_Jonzor:/usr/local/apache2/htdocs/assets/icons:ro

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
